name: "Update dependencies"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build-ghc:
    strategy:
      matrix:
        ghc: ['865', '884', '8104', '8106', '8107', '901']
    name: "Build ghc${{ matrix.ghc }}"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build ghc${{ matrix.ghc }}
        run:
          nix build --print-build-logs --no-link .#pkgs.x86_64-darwin.haskell-nix.compiler.ghc${{ matrix.ghc }}
  update:
    name: "Update dependencies"
    needs: [build-ghc]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unlock secrets
        run: |
          brew install git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check flakes
        run: |
          nix flake show
      - name: Update dependencies
        run: |
          nix flake update --recreate-lock-file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          nix build --print-build-logs --no-link .#darwinConfigurations.ghActions.system
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Automatic dependencies update
